coverage:
  round: up
  range: 50..100

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: "5%"

    patch:
      default:
        enabled: false
    changes:
      default:
        enabled: false
